c = set( i for i in range(1,6))
d = {item: item for item in c}
l = list(c)
t = tuple(c)
print(f"Conjunto: {c}")
print("#"*30)
print(f"Diccionario: {d}")
print("#"*30)
print(f"Conjunto congelado: {frozenset(c)}")
print("#"*30)
print(f"Lista: {l}")
print("#"*30)
print(f"los conjuntos no se pueden ordenar, pero si crear una lista y ordenarlos \n pero dejaria de ser un conjunto {sorted(l)}")
print("#"*30)
print(f"Tupla: {t}")
print("#"*30)
li=[6,7]
c.update(set(li))
print(f"para agregar la lista {li} al conjunto  \n solo hay que usar el metodo update() {c}")
print("#"*30)
